version: '3'
services:
  db:
    image: 'mongo'
    container_name: chat-db 
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=chat-db
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    volumes:
      - "./init:/docker-entrypoint-initdb.d"
      - "./mongo-volume:/data/db"
